// Code generated by go-enum DO NOT EDIT.
// Version: 0.3.9
// Revision: 5a95b1bbcaf1f8f32542725929d84acdf48e0259
// Build Date: 2021-11-05T17:00:39Z
// Built By: goreleaser

package db

import (
	"fmt"
)

const (
	// MovieStatusWatched is a MovieStatus of type Watched.
	MovieStatusWatched MovieStatus = iota
	// MovieStatusUnwatched is a MovieStatus of type Unwatched.
	MovieStatusUnwatched
)

const _MovieStatusName = "WatchedUnwatched"

var _MovieStatusMap = map[MovieStatus]string{
	MovieStatusWatched:   _MovieStatusName[0:7],
	MovieStatusUnwatched: _MovieStatusName[7:16],
}

// String implements the Stringer interface.
func (x MovieStatus) String() string {
	if str, ok := _MovieStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("MovieStatus(%d)", x)
}

var _MovieStatusValue = map[string]MovieStatus{
	_MovieStatusName[0:7]:  MovieStatusWatched,
	_MovieStatusName[7:16]: MovieStatusUnwatched,
}

// ParseMovieStatus attempts to convert a string to a MovieStatus
func ParseMovieStatus(name string) (MovieStatus, error) {
	if x, ok := _MovieStatusValue[name]; ok {
		return x, nil
	}
	return MovieStatus(0), fmt.Errorf("%s is not a valid MovieStatus", name)
}
